### ISSUE TITLE
Export SIGRTMIN() and SIGRTMAX() as public 

### ISSUE THREAD

**Issue by iulianbarbu** [rust-vmm/vmm-sys-util#63] opened 2019-12-11 18:00 UTC
SIGRTMIN() and SIGRTMAX() methods, which returns base signums for registering real-time signals are private, inside vmm-sys-util crate. It would be beneficial if these methods are public, to be consumed as well when signal handlers are registered with methods from this crate.

**Comment by andreeaflorescu** [comment] 2019-12-11 18:06
Duplicate of #62

**Closed by andreeaflorescu** 2019-12-11 18:06 UTC
